export const RETRIEVE_LATEST_MOVIES_SUCCESS = 'RETRIEVE_LATEST_MOVIES_SUCCESS';
export const RETRIEVE_LATEST_MOVIES_FAILURE = 'RETRIEVE_LATEST_MOVIES_FAILURE';
export const RETRIEVE_LATEST_MOVIES_FETCHING = 'RETRIEVE_LATEST_MOVIES_FETCHING';

export const RETRIEVE_UPCOMING_MOVIES_SUCCESS = 'RETRIEVE_UPCOMING_MOVIES_SUCCESS';
export const RETRIEVE_UPCOMING_MOVIES_FAILURE = 'RETRIEVE_UPCOMING_MOVIES_FAILURE';
export const RETRIEVE_UPCOMING_MOVIES_FETCHING = 'RETRIEVE_UPCOMING_MOVIES_FETCHING';