export const RETRIEVE_FAILURE = 'RETRIEVE_FAILURE';
export const RETRIEVE_FETCHING = 'RETRIEVE_FETCHING';

export const RETRIEVE_LATEST_MOVIES_SUCCESS = 'RETRIEVE_LATEST_MOVIES_SUCCESS';
export const RETRIEVE_UPCOMING_MOVIES_SUCCESS = 'RETRIEVE_UPCOMING_MOVIES_SUCCESS';